apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "false"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.cluster.name }}-calico
  namespace: {{ .Release.Namespace }}
spec:
  catalog: default-test
  {{- include "kubeconfig" . | nindent 2 }}
  {{- include "config" . | nindent 2 }}
  name: calico
  namespace: kube-system
  version: 0.2.1-bb1e2721e52beb0f5dd61227e4da5d58d55697ab
