apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.clusterName }}-cloud-provider-openstack
  namespace: {{ .Release.Namespace }}
spec:
  catalog: default
  {{- include "kubeconfig" . | nindent 2 }}
  {{- include "config" . | nindent 2 }}
    secret:
      name: {{ .Values.clusterName }}-cluster-values
      namespace: {{ .Release.Namespace }}
  name: cloud-provider-openstack-app
  namespace: kube-system
  userConfig:
    configMap:
      name: {{ .Values.clusterName }}-cloud-provider-openstack-user-values
      namespace: {{ .Release.Namespace }}
  version: 0.2.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.clusterName }}-cloud-provider-openstack-user-values
  namespace: {{ .Release.Namespace }}
data:
  values: |
    openstack-cinder-csi:
      clusterID: giant_swarm_cluster_{{ .Values.managementCluster }}_{{ .Values.clusterName }}
    openstack-cloud-controller-manager:
      controllerExtraArgs: |-
        - --cluster-name=giant_swarm_cluster_{{ .Values.managementCluster }}_{{ .Values.clusterName }}


