apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.clusterName }}-cloud-provider-openstack
  namespace: {{ .Release.Namespace }}
spec:
  catalog: default
  {{- include "kubeconfig" . | nindent 2 }}
  {{- include "config" . | nindent 2 }}
    secret:
      name: {{ .Values.clusterName }}-cluster-values
      namespace: {{ .Release.Namespace }}
  name: cloud-provider-openstack-app
  namespace: kube-system
  version: 0.2.0
