apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.clusterName }}-net-exporter
  namespace: {{ .Release.Namespace }}
spec:
  catalog: default
  {{- include "kubeconfig" . | nindent 2 }}
  {{- include "config" . | nindent 2 }}
  name: net-exporter
  namespace: kube-system
  version: 1.10.3
  userConfig:
    configMap:
      name: {{ .Values.clusterName }}-net-exporter-user-values
      namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.clusterName }}-net-exporter-user-values
  namespace: {{ .Release.Namespace }}
data:
  values: |
    dns:
      service": "kube-dns"
