{{- if .Values.oidc.enabled -}}
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.clusterName }}-nginx-ingress-controller
  namespace: {{ .Release.Namespace }}
spec:
  catalog: control-plane-catalog # TODO: push to default catalog
  {{- include "kubeconfig" . | nindent 2 }}
  {{- include "config" . | nindent 2 }}
  name: nginx-ingress-controller
  namespace: kube-system
  version: 2.8.0
{{ end -}}
