name: default-apps-openstack
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/default-apps-openstack
  tag: v0.0.1
  pullPolicy: IfNotPresent
