clusterName: ""
organization: ""
managementCluster: ""

userConfig:
  netExporter:
    configMap:
      values: |
        dns:
          service: "kube-dns"

apps:
  calico:
    appName: calico
    chartName: calico
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    version: 0.2.1
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    version: 2.1.0
  cloudProviderOpenstack:
    appName: cloud-provider-openstack
    chartName: cloud-provider-openstack-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    version: 0.2.2
  kubeStateMetrics:
    appName: kube-state-metrics
    chartName: kube-state-metrics-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    version: 1.7.0
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    version: 1.6.0
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    version: 1.10.3
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    version: 1.9.0
