clusterName: ""
organization: ""
managementCluster: ""

userConfig:
  cloudProviderOpenstack:
    configMap:
      values: |
        openstack-cinder-csi:
          clusterID: giant_swarm_cluster_{{ .Values.managementCluster }}_{{ .Values.clusterName }}
        openstack-cloud-controller-manager:
          controllerExtraArgs: |-
            - --cluster-name=giant_swarm_cluster_{{ .Values.managementCluster }}_{{ .Values.clusterName }}
  nodeExporter:
    configMap:
      values: |
        disableConntrackCollector: true
        disableNvmeCollector: true

apps:
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-exporter
    version: 2.2.0
  certManager:
    appName: cert-manager
    chartName: cert-manager-app
    catalog: default-test
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-manager-app
    version: 2.17.0-935f68f554b4b285f7e8aab718d09dff5eac5fe1
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.2.6
  cloudProviderOpenstack:
    appName: cloud-provider-openstack
    chartName: cloud-provider-openstack-app
    catalog: default-test
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cloud-provider-openstack-app
    version: 0.6.2-bc9fe1b6e5d023a5b536d3d13f0777877dfafb13
  clusterResources:
    appName: cluster-resources
    chartName: cluster-resources
    catalog: default-test
    clusterValues:
      configMap: false
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cluster-resources-app
    version: 0.1.1-ca3ec63b7b263f8501ffaea2eccf0c3a0cc030f0
  coreDNS:
    appName: coredns
    chartName: coredns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/coredns-app
    version: 1.11.0
  csiExternalSnapshotter:
    appName: csi-external-snapshotter
    chartName: csi-external-snapshotter-app
    catalog: default-test
    clusterValues:
      configMap: false
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/csi-external-snapshotter-app
    version: 0.2.0-75e22d008591d0fcba8bfe74c3f2ad48848f501e
  kubeStateMetrics:
    appName: kube-state-metrics
    chartName: kube-state-metrics
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/kube-state-metrics-app
    version: 1.12.1
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/metrics-server-app
    version: 1.8.0
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/net-exporter
    version: 1.10.3
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/node-exporter-app
    version: 1.11.0
