clusterName: ""
organization: ""
managementCluster: ""

userConfig:
  cloudProviderOpenstack:
    configMap:
      values: |
        openstack-cinder-csi:
          clusterID: giant_swarm_cluster_{{ .Values.managementCluster }}_{{ .Values.clusterName }}
        openstack-cloud-controller-manager:
          controllerExtraArgs: |-
            - --cluster-name=giant_swarm_cluster_{{ .Values.managementCluster }}_{{ .Values.clusterName }}
  netExporter:
    configMap:
      values: |
        dns:
          service: kube-dns
  nodeExporter:
    configMap:
      values: |
        disableConntrackCollector: true
        disableNvmeCollector: true

apps:
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-exporter
    version: 2.1.0
  certManager:
    appName: cert-manager
    chartName: cert-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-manager-app
    version: 2.15.2
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.2.6
  cloudProviderOpenstack:
    appName: cloud-provider-openstack
    chartName: cloud-provider-openstack-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cloud-provider-openstack-app
    version: 0.6.2
  clusterResources:
    appName: cluster-resources
    chartName: cluster-resources
    catalog: default
    clusterValues:
      configMap: false
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cluster-resources-app
    version: 0.1.0
  csiExternalSnapshotter:
    appName: csi-external-snapshotter
    chartName: csi-external-snapshotter-app
    catalog: default
    clusterValues:
      configMap: false
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/csi-external-snapshotter-app
    version: 0.2.0
  kubeStateMetrics:
    appName: kube-state-metrics
    chartName: kube-state-metrics-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/kube-state-metrics-app
    version: 1.11.0
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/metrics-server-app
    version: 1.8.0
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/net-exporter
    version: 1.10.3
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/node-exporter-app
    version: 1.11.0
